### ISSUE TITLE
Prefetch improvements

### ISSUE THREAD

**Issue by gperdomor** [Bluzzi/Next-Server-Actions#1]
Thank you for this repo... I have one question...

Any reason for doing this?:

```typescript
for (const query of queries) {
    await queryClient.prefetchQuery(query);
}
```

Instead of:

```typescript
await Promise.all(queries.map(query => queryClient.prefetchQuery(query)))
```

**Comment by Bluzzi** [comment]
Hello, thank you for this issue.

There's no specific reason why I didn't use `Promise.all()` and given the way TanStack Query works, I don't think its use is bad, the dependencies will be managed by TanStack Query anyway.

So I think `Promise.all()` is a good optimisation without any disadvantages in this case.

If you're interested, don't hesitate to open a PR for this change, otherwise I'll do it in the next few days.

**Comment by gperdomor** [comment]
The only disadvantage of the `for` syntax is that the promises are resolved sequentially, so the second query will start after the first one is resolved, and so on... With the `Promise.all` syntax are handled with concurrency...  I will send a MR
